NumPy Exercises

In [3]:
import numpy as np
# create an array of 10 zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# create an array of 10 ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
# createan array of 10 fives
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [6]:
# create an array of the integars from 10 to 50
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [9]:
# create an array of all the even integers from 10 to 50
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [10]:
# create a 3X3 matrix values ranging from 0 to 8
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
# create a 3X3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [1]:
import numpy as np 

In [2]:
myList = [1,2,3]
myList

[1, 2, 3]

In [3]:
np.array(myList)

array([1, 2, 3])

In [4]:
myl2 = [[1,2,3],[1,2,3],[4,5,6]]
myl2

[[1, 2, 3], [1, 2, 3], [4, 5, 6]]

In [5]:
np.array(myl2)

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [6]:
list(range(0,11))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [9]:
list(range(0,11,4))

[0, 4, 8]

In [11]:
np.arange(0,11,2) # array range b 0---11 not execlte end 

array([ 0,  2,  4,  6,  8, 10])

In [17]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.eye(4) # method eye create matix 3x3 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
# Linspace
np.linspace(0,100,6)

array([  0.,  20.,  40.,  60.,  80., 100.])

In [21]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [23]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [25]:
np.random.rand(4) # creat random number 4 

array([0.61376055, 0.99728162, 0.52668058, 0.49159239])

In [26]:
np.random.rand(4,4) # creat random number matrix 3x3

array([[0.40220753, 0.73873399, 0.83142968, 0.05917301],
       [0.78242099, 0.47180004, 0.45780126, 0.64254796],
       [0.91287289, 0.66141261, 0.13729014, 0.63794383],
       [0.49426194, 0.71139125, 0.25939705, 0.3638245 ]])

In [27]:
np.random.randn(2) # creat normal number in the normoal disteibution  

array([0.62387475, 0.82704572])

In [28]:
np.random.randn(3,3)

array([[-0.03800124, -1.52974559,  0.24718362],
       [ 0.53009296,  0.22582425, -1.29232124],
       [-1.43903373,  0.23105709, -0.70015973]])

In [31]:
np.random.randn(5, 5)

array([[ 0.21814143,  2.06801902, -1.05447038,  0.80677215, -1.41264809],
       [-1.75484153, -0.62492254,  0.45059422, -1.11739457, -0.52509196],
       [ 0.52172541,  0.51291881, -1.05006451,  0.30767185,  1.71889674],
       [-2.70042884,  0.17073805,  0.37891068, -0.39722931, -0.58342667],
       [ 0.95849037,  1.92083907, -0.38699892,  0.40195445,  0.44081764]])

In [34]:
# random integers for low to high
np.random.randint(1,10)

4

In [37]:
np.random.randint(1,100,(5,5))

array([[29, 42, 76, 60, 32],
       [ 8, 95, 11, 16, 52],
       [53, 38, 41, 95, 70],
       [20,  6, 52, 35, 16],
       [61, 10, 56, 87, 84]])

In [39]:
np.random.randint(1,50,(4,4))

array([[48, 19, 19, 37],
       [ 6, 20, 20, 27],
       [26, 15, 38, 35],
       [15,  8,  6, 45]])

In [40]:
# max , min , argmax , argmin 
#  useful methods for finding max or min or find index location using argmax, argmin
ll = np.random.randint(1,100,(5,5))
ll

array([[16, 18, 14, 43, 64],
       [75, 60, 51, 15, 78],
       [26, 16, 52, 36,  4],
       [53, 19, 72, 13, 19],
       [55, 99, 20, 82, 73]])

In [41]:
ll.max()

99

In [42]:
ll.min()

4

In [43]:
ll.argmax()

21

In [44]:
ll.argmin()

14

In [46]:
# Reshape 
#return an array contining the same data with a new shape
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)
linarr = np.linspace(0,2,11)

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [48]:
arr.shape

(25,)

In [49]:
ranarr

array([15, 22, 46, 10, 15, 37,  4, 47, 13,  8])

In [50]:
ranarr.shape

(10,)

In [51]:
linarr

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [52]:
linarr.shape

(11,)

In [54]:
reshaped = arr.reshape(5,5)
reshaped

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [55]:
reshaped.shape

(5, 5)

In [56]:
reshaped.reshape(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [57]:
reshaped.reshape(25).shape

(25,)

In [58]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [59]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [60]:
arr.reshape(1,25).shape

(1, 25)

In [61]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [62]:
arr.reshape(25,1).shape

(25, 1)

# Numpy Indexing and Selection

In [63]:
arr = np.arange(30,40)
arr

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [64]:
arr[8]

38

In [66]:
# git value in range 
arr[:2]

array([30, 31])

In [67]:
arr[2:5]

array([32, 33, 34])

In [68]:
arr[0:5]

array([30, 31, 32, 33, 34])

In [69]:
arr[:5]

array([30, 31, 32, 33, 34])

In [70]:
arr[3:]

array([33, 34, 35, 36, 37, 38, 39])

In [71]:
arr[3:7]

array([33, 34, 35, 36])

In [72]:
arr[3:7:2]

array([33, 35])

In [73]:
arr

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [74]:
arr[2:4] = 100

In [75]:
arr

array([ 30,  31, 100, 100,  34,  35,  36,  37,  38,  39])

In [77]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]) )
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [78]:
arr_2d[1]

array([20, 25, 30])

In [79]:
arr_2d[1][0]

20

In [80]:
arr_2d[1,0]

20

In [81]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [83]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [84]:
arr_2d[2]

array([35, 40, 45])

In [85]:
arr_2d[2,:]

array([35, 40, 45])

In [86]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [87]:
arr_2d[::-1 , ::]

array([[35, 40, 45],
       [20, 25, 30],
       [ 5, 10, 15]])

In [88]:
arr_2d[:,::-1]

array([[15, 10,  5],
       [30, 25, 20],
       [45, 40, 35]])

In [89]:
arr_2d[::,::-1]

array([[15, 10,  5],
       [30, 25, 20],
       [45, 40, 35]])

In [90]:
arr_2d[::-1,::-1]

array([[45, 40, 35],
       [30, 25, 20],
       [15, 10,  5]])

# Fancy Indexing

In [92]:
arr2d = np.random.randint(1,100,(10,10))
arr2d

array([[52, 98, 42, 95, 52, 82, 97, 84, 25,  8],
       [66, 99, 59,  5, 94, 43, 78, 25, 36, 80],
       [42,  7, 10, 59, 20, 13, 95, 81, 19, 78],
       [99,  5, 19, 65, 26, 21, 90,  4,  5, 40],
       [13, 64,  9, 39, 24, 97,  6, 78, 16, 72],
       [35,  4, 13, 28, 20, 35,  4, 35, 72, 58],
       [78, 58,  6, 82, 99, 28, 74, 95, 76, 86],
       [48, 82, 66, 28, 92, 93, 82, 83, 17,  3],
       [89, 45, 88, 77, 88, 59, 23, 41, 21, 62],
       [35, 83, 26, 31, 18, 89, 61, 11,  5, 25]])

In [94]:
arr2d[[1,2,3,4]]

array([[66, 99, 59,  5, 94, 43, 78, 25, 36, 80],
       [42,  7, 10, 59, 20, 13, 95, 81, 19, 78],
       [99,  5, 19, 65, 26, 21, 90,  4,  5, 40],
       [13, 64,  9, 39, 24, 97,  6, 78, 16, 72]])

In [95]:
arr2d[[0,2,4,6,8]]

array([[52, 98, 42, 95, 52, 82, 97, 84, 25,  8],
       [42,  7, 10, 59, 20, 13, 95, 81, 19, 78],
       [13, 64,  9, 39, 24, 97,  6, 78, 16, 72],
       [78, 58,  6, 82, 99, 28, 74, 95, 76, 86],
       [89, 45, 88, 77, 88, 59, 23, 41, 21, 62]])

In [96]:
arr2d[[1,4,6,8],2:5]

array([[59,  5, 94],
       [ 9, 39, 24],
       [ 6, 82, 99],
       [88, 77, 88]])

# selection

In [99]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True])

In [102]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True])

In [103]:
arr[bool_arr]

array([5, 6, 7, 8, 9])

In [104]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
arr[arr>=5]

array([5, 6, 7, 8, 9])

In [106]:
x=3
arr[arr>x]

array([4, 5, 6, 7, 8, 9])

In [107]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
arr[arr % 2 ==0]

array([2, 4, 6, 8])

# NumPy Operation

1- Arithmetic and logic
   1.1)Arithmetic
   1.2)Logic
2- Univesal Array Function
   2.1)max,min,avarage,sum
   2.2)power,sqrt,exp,log
   2.3)sin,cos,tan
   2.4)dot product
3- Combine and Split data


In [109]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
arr+3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [111]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [112]:
arr-10

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [113]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [114]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [115]:
arr/arr

C:\Users\ah407\AppData\Local\Temp\ipykernel_15824\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [116]:
1/arr

C:\Users\ah407\AppData\Local\Temp\ipykernel_15824\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [117]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

Logic

In [118]:
arr>3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [120]:
arr!=3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True])

In [122]:
arr = np.random.randint(0,10,(3,3))
arr

array([[9, 5, 6],
       [6, 1, 1],
       [0, 1, 2]])

In [123]:
arr+3

array([[12,  8,  9],
       [ 9,  4,  4],
       [ 3,  4,  5]])

In [124]:
arr-2

array([[ 7,  3,  4],
       [ 4, -1, -1],
       [-2, -1,  0]])

In [125]:
arr*3

array([[27, 15, 18],
       [18,  3,  3],
       [ 0,  3,  6]])

In [126]:
3*arr

array([[27, 15, 18],
       [18,  3,  3],
       [ 0,  3,  6]])

In [127]:
arr

array([[9, 5, 6],
       [6, 1, 1],
       [0, 1, 2]])

In [129]:
arr + 3 * arr

array([[36, 20, 24],
       [24,  4,  4],
       [ 0,  4,  8]])

In [130]:
arr*arr

array([[81, 25, 36],
       [36,  1,  1],
       [ 0,  1,  4]])

In [131]:
arr


array([[9, 5, 6],
       [6, 1, 1],
       [0, 1, 2]])

In [134]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
matrix = np.random.randint(0,100,(5,3))
matrix

array([[62, 28, 14],
       [88, 72, 22],
       [58, 36, 94],
       [60, 71, 47],
       [73, 77,  8]])

In [137]:
np.max(arr)

9

In [138]:
np.max(matrix)

94

In [139]:
np.max(matrix, axis=0)

array([88, 77, 94])

In [140]:
np.max(matrix, axis=1)

array([62, 88, 94, 71, 77])

In [141]:
np.min(arr)

0

In [142]:
np.min(matrix)

8

In [143]:
np.min(matrix , axis=1)

array([14, 22, 36, 47,  8])

In [144]:
np.average(arr)

4.5

In [145]:
np.average(matrix)

54.0

In [146]:
np.sum(arr)

45

In [147]:
np.sum(matrix)

810

Sqrt , Exp , Log , Sin

In [148]:
np.power(arr,2)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [149]:
np.power(matrix,3)

array([[238328,  21952,   2744],
       [681472, 373248,  10648],
       [195112,  46656, 830584],
       [216000, 357911, 103823],
       [389017, 456533,    512]], dtype=int32)

In [150]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [151]:
np.sqrt(matrix)

array([[7.87400787, 5.29150262, 3.74165739],
       [9.38083152, 8.48528137, 4.69041576],
       [7.61577311, 6.        , 9.69535971],
       [7.74596669, 8.42614977, 6.8556546 ],
       [8.54400375, 8.77496439, 2.82842712]])

In [152]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [153]:
np.exp(matrix)

array([[8.43835667e+26, 1.44625706e+12, 1.20260428e+06],
       [1.65163625e+38, 1.85867175e+31, 3.58491285e+09],
       [1.54553894e+25, 4.31123155e+15, 6.66317622e+40],
       [1.14200739e+26, 6.83767123e+30, 2.58131289e+20],
       [5.05239363e+31, 2.75851345e+33, 2.98095799e+03]])

In [154]:
angle = np.linspace(0,360,9).reshape(3,3)
angle

array([[  0.,  45.,  90.],
       [135., 180., 225.],
       [270., 315., 360.]])

In [155]:
angle = (angle*2*np.pi)/360
angle

array([[0.        , 0.78539816, 1.57079633],
       [2.35619449, 3.14159265, 3.92699082],
       [4.71238898, 5.49778714, 6.28318531]])

In [156]:
np.sin(angle)

array([[ 0.00000000e+00,  7.07106781e-01,  1.00000000e+00],
       [ 7.07106781e-01,  1.22464680e-16, -7.07106781e-01],
       [-1.00000000e+00, -7.07106781e-01, -2.44929360e-16]])

In [157]:
np.cos(angle)

array([[ 1.00000000e+00,  7.07106781e-01,  6.12323400e-17],
       [-7.07106781e-01, -1.00000000e+00, -7.07106781e-01],
       [-1.83697020e-16,  7.07106781e-01,  1.00000000e+00]])

In [160]:
# dot poduct 
mat = np.arange(9).reshape(3,3)
vec1 = np.array([1,2,3])
mat


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [161]:
vec1

array([1, 2, 3])

In [163]:
np.dot(vec1,mat)

array([24, 30, 36])

In [164]:
vec1.dot(mat)

array([24, 30, 36])

In [165]:
import numpy as np


In [166]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [167]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [168]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [170]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [171]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [185]:
np.arange(9).reshape

<function ndarray.reshape>

In [186]:
import numpy as np

In [187]:
np.arange(9).reshape

<function ndarray.reshape>

In [178]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [188]:
np.random.rand(1)

array([0.20673879])

In [189]:
np.random.randn(25)

array([-1.31335077, -0.81237534, -0.80771997,  1.20016562, -0.79738865,
        0.72201154,  0.21256894, -0.98321876,  2.1116212 , -1.3878693 ,
        0.11520227,  1.77196358,  1.13346953, -0.345554  ,  1.06951273,
        0.14847784, -0.373321  , -0.89421205,  0.49925885, -0.88436817,
       -0.16925284,  0.35825616, -0.17205469, -0.24275821,  0.10583135])

In [190]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [192]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [193]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [194]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [195]:
mat[3,4]

20

In [196]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [197]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [198]:
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [199]:
mat.sum()

325

In [200]:
mat.std()

7.211102550927978

In [201]:
mat.sum(axis = 0)

array([55, 60, 65, 70, 75])